# Dependabot configuration for Organizr Docker
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor PHP dependencies in the api directory
  - package-ecosystem: "composer"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "composer"
      include: "scope"
    reviewers:
      - "GitTimeraider"
    labels:
      - "dependencies"
      - "php"

  # Monitor Docker base images and dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "GitTimeraider"
    labels:
      - "dependencies"
      - "docker"

  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "GitTimeraider"
    labels:
      - "dependencies"
      - "github-actions"
