name: Development Checks

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning

  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: organizr-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test container startup
      run: |
        docker run -d --name organizr-test \
          -p 8080:80 \
          -e PUID=1000 \
          -e PGID=1000 \
          organizr-test:latest
        
        # Wait for container to start
        sleep 30
        
        # Check if container is running
        if ! docker ps | grep organizr-test; then
          echo "Container failed to start"
          docker logs organizr-test
          exit 1
        fi
        
        # Test HTTP response
        if ! curl -f http://localhost:8080; then
          echo "HTTP check failed"
          docker logs organizr-test
          exit 1
        fi
        
        echo "Container test passed!"
        docker stop organizr-test

  check-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate docker-compose.yml
      run: |
        docker-compose -f docker-compose.yml config -q
        docker-compose -f compose.local.yml config -q

  check-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
