name: Legacy Docker (disabled)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This legacy workflow is disabled. Use docker-publish.yml and docker-pr.yml."

